### ISSUE TITLE
Смена работы с переменными окружения

### ISSUE THREAD

**Issue by ilya-grigoriev** [blago-white/django-online-chat#1]
- Думаю, что лучше использовать модуль `dotenv` вместо `os.environ`.
- Использование `os.environ` имеет более глобальный характер (берутся переменные самой операционной системы).

**Comment by blago-white** [comment]
**Огромное спасибо за обратную связь**, проект запускается через виртуальное окружение (venv), и думаю вероятность коллизий имён переменных мала, (если вы про это), а dotenv я использую, для подгрузки переменных из .env файла

**Comment by ilya-grigoriev** [comment]
> **Огромное спасибо за обратную связь**, проект запускается через виртуальное окружение (venv), и думаю вероятность коллизий имён переменных мала, (если вы про это), а dotenv я использую, для подгрузки переменных из .env файла

Я имел в виду не совсем коллизию, а сам факт того, что для получения переменных окружения читаются ГЛОБАЛЬНЫЕ ПЕРЕМЕННЫЕ, хотя для этой задачи вполне подошёл бы `dotenv`, который читает ЛОКАЛЬНЫЕ ПЕРЕМЕННЫЕ (назовём их так) из файла `.env`.

**Comment by ilya-grigoriev** [comment]
- Лично я бы не стал хранить `POSTGRES_PASSWORD` в ГЛОБАЛЬНЫХ ПЕРЕМЕННЫХ ОКРУЖЕНИЯ, т.к. это позволило бы легко получить мой пароль. 
- А вот с `dotenv` было бы куда удобнее и изменять значение, и не бояться за данные.

**Comment by blago-white** [comment]
Понятно, спасибо за информацию, учту этот нюанс
